// Code generated by protoc-gen-go. DO NOT EDIT.
// source: file.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Req struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Req) Reset()         { *m = Req{} }
func (m *Req) String() string { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()    {}
func (*Req) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{0}
}

func (m *Req) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Req.Unmarshal(m, b)
}
func (m *Req) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Req.Marshal(b, m, deterministic)
}
func (m *Req) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Req.Merge(m, src)
}
func (m *Req) XXX_Size() int {
	return xxx_messageInfo_Req.Size(m)
}
func (m *Req) XXX_DiscardUnknown() {
	xxx_messageInfo_Req.DiscardUnknown(m)
}

var xxx_messageInfo_Req proto.InternalMessageInfo

func (m *Req) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type Resp struct {
	Path                 string   `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Md5                  string   `protobuf:"bytes,5,opt,name=md5,proto3" json:"md5,omitempty"`
	IsDir                bool     `protobuf:"varint,6,opt,name=IsDir,proto3" json:"IsDir,omitempty"`
	Content              []byte   `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resp) Reset()         { *m = Resp{} }
func (m *Resp) String() string { return proto.CompactTextString(m) }
func (*Resp) ProtoMessage()    {}
func (*Resp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{1}
}

func (m *Resp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resp.Unmarshal(m, b)
}
func (m *Resp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resp.Marshal(b, m, deterministic)
}
func (m *Resp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resp.Merge(m, src)
}
func (m *Resp) XXX_Size() int {
	return xxx_messageInfo_Resp.Size(m)
}
func (m *Resp) XXX_DiscardUnknown() {
	xxx_messageInfo_Resp.DiscardUnknown(m)
}

var xxx_messageInfo_Resp proto.InternalMessageInfo

func (m *Resp) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Resp) GetMd5() string {
	if m != nil {
		return m.Md5
	}
	return ""
}

func (m *Resp) GetIsDir() bool {
	if m != nil {
		return m.IsDir
	}
	return false
}

func (m *Resp) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func init() {
	proto.RegisterType((*Req)(nil), "demo.req")
	proto.RegisterType((*Resp)(nil), "demo.resp")
}

func init() { proto.RegisterFile("file.proto", fileDescriptor_9188e3b7e55e1162) }

var fileDescriptor_9188e3b7e55e1162 = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xcb, 0xcc, 0x49,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x49, 0x49, 0xcd, 0xcd, 0x57, 0x92, 0xe4, 0x62,
	0x2e, 0x4a, 0x2d, 0x14, 0x12, 0xe2, 0x62, 0x29, 0x48, 0x2c, 0xc9, 0x90, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x0c, 0x02, 0xb3, 0x95, 0x62, 0xb8, 0x58, 0x8a, 0x52, 0x8b, 0x0b, 0xe0, 0x72, 0x2c, 0x08,
	0x39, 0x21, 0x01, 0x2e, 0xe6, 0xdc, 0x14, 0x53, 0x09, 0x56, 0xb0, 0x10, 0x88, 0x29, 0x24, 0xc2,
	0xc5, 0xea, 0x59, 0xec, 0x92, 0x59, 0x24, 0xc1, 0xa6, 0xc0, 0xa8, 0xc1, 0x11, 0x04, 0xe1, 0x08,
	0x49, 0x70, 0xb1, 0x27, 0xe7, 0xe7, 0x95, 0xa4, 0xe6, 0x95, 0x48, 0xb0, 0x2b, 0x30, 0x6a, 0xf0,
	0x04, 0xc1, 0xb8, 0x4e, 0x6c, 0x51, 0x2c, 0x7a, 0xfa, 0x05, 0x49, 0x49, 0x6c, 0x60, 0xd7, 0x18,
	0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x75, 0xad, 0x51, 0xbd, 0x9b, 0x00, 0x00, 0x00,
}
